#import "./anexos/matriz-consistencia.typ": master
#pagebreak()
= Problema de investigación // maximo una pagina

La detección de neumonía a partir de radiografías sigue dependiendo en gran medida de la interpretación manual de especialistas, lo cual puede generar retrasos en el diagnóstico y, en ocasiones, equivocaciones de alta gravedad que ponen en riesgo la salud del paciente. Aunque herramientas tecnológicas han ganado terreno en algunas áreas, aún persiste una brecha significativa en la calidad de atención, especialmente en zonas rurales, donde la disponibilidad de médicos especializados es limitada. 

El diagnóstico erróneo o tardío de neumonía tiene consecuencias graves, ya que puede derivar en complicaciones o incluso muertes, como se ha evidenciado en estudios previos. Por ejemplo, en un estudio realizado en Turquía, se observó que, debido a la sobrecarga de solicitudes durante la pandemia, la tasa de errores de interpretación alcanzó un 18.5% en los primeros 60 días del brote @Koc2021. Este tipo de error es aún más pronunciado en regiones rurales, donde el acceso a atención médica especializada es más limitado. De hecho, en Ecuador, la tasa de incidencia de cuadro neumónico adquirido en la comunidad fue de 16.83 por cada 10,000 habitantes en 2019, siendo los niños menores de cinco años y adultos mayores de 65 años los más afectados. La mortalidad hospitalaria oscila entre el 4% y el 18%, pero puede llegar hasta el 50% en casos graves que requieren ingreso en la Unidad de Terapia Intensiva @leon2023. Además, en Perú, durante diciembre de 2020, 61 de 149 clínicas y hospitales se encontraban sin capacidad para realizar diagnósticos, lo que reflejó la incapacidad del sistema de salud para responder adecuadamente a la crisis sanitaria @elcomercio2020. Más recientemente, en 2024, el Instituto Nacional de Salud del Niño (INSN) enfrentó una grave escasez de médicos radiólogos, lo que comprometió la capacidad del hospital para atender este tipo de consultas @peru21-2024. Además, según datos del Ministerio de Salud, existen 17 médicos por cada 10 000 habitantes, lo que genera sobrecarga y acceso limitado a servicios médicos, especialmente en zonas remotas donde más se necesita atención @stakeholder2024.

Ante este panorama, cobra relevancia explorar cómo los modelos de deep learning pueden aportar una solución, lo que lleva a formular la siguiente interrogante: #master.at(0).problema
