#import "@local/utp-doc:1.0.0": pc

#pagebreak()

= Revisión de la literatura actual o estado del arte // maximo 5 paginas
Diversos estudios y proyectos han abordado la necesidad de desarrollar sistemas de detección de neumonía usando modelos de Deep Learning, demostrando su efectividad para diagnosticar la enfermedad.

// contexto internacional 8 ------------------------------------------

// todo: agregar a marco teorico CNN
// 1 sin indicadores ✅
//* introducción */ #pc[@hwang2020] en su estudio, presenta una revisión sobre el uso del aprendizaje profundo en radiología, centrándose en radiografías de tórax y tomografías computarizadas. /* objetivo */ El objetivo fue introducir las aplicaciones clínicas potenciales de esta tecnología en la práctica clínica diaria. /* procedimiento */ Para ello, los autores realizaron una revisión narrativa de la literatura científica sobre algoritmos de Deep Learning, especialmente CNN, además de explorar su integración en distintos flujos de trabajo clínico. /* resultado */ Encontraron que el Deep Learning ha demostrado un rendimiento prometedor, comparable o superior al de radiólogos expertos en tareas como la detección de enfermedades pulmonares, cribado de cáncer, extracción de biomarcadores pronósticos y mejora de calidad de imagen. /* conclusion */ Concluyen que, aunque todavía emergente, esta tecnología tiene un alto potencial transformador en la radiología torácica, y que los radiólogos deben comprender sus beneficios y limitaciones para liderar su integración. /* limitaciones */ Los autores mencionan que las principales barreras identificadas fueron la falta de explicabilidad de los algoritmos, la validación insuficiente en entornos clínicos reales, la falta de evidencia de impacto en los resultados del paciente y la dificultad de integración con sistemas clínicos existentes.

/* introducción */ #pc[@hwang2020] presenta una revisión sobre el uso de deep learning en radiología, con foco en radiografías de tórax y tomografías computarizadas. /* objetivo */ Introducir las aplicaciones clínicas del deep learning en la práctica diaria. /* procedimiento */ Se realizó una revisión narrativa de literatura sobre algoritmos CNN y su integración en flujos clínicos. /* resultado */ Se halló que el deep learning puede igualar o superar a radiólogos expertos en detección de enfermedades pulmonares, cribado, pronóstico y mejora de imagen. /* conclusion */ Aunque emergente, esta tecnología tiene alto potencial en radiología torácica, y su adopción requiere que los radiólogos comprendan sus capacidades y límites. /* limitaciones */ Las barreras incluyen falta de explicabilidad, escasa validación clínica, poca evidencia de impacto en pacientes y dificultad de integración con sistemas existentes.

// 2 indicadores ✅
//* introducción */ En estudios previos realizados por #pc[@kim2020], se evaluó la utilidad clínica de un algoritmo comercial de deep learning en la detección de neumonía mediante radiografías de tórax en pacientes con enfermedad respiratoria que acuden al servicio de urgencias. /* objetivo */ El objetivo del estudio fue determinar el rendimiento diagnóstico del algoritmo y su valor añadido como herramienta de apoyo para médicos no radiólogos. /* procedimiento */ Con ese objetivo, se realizó un estudio en un hospital militar con 377 pacientes, utilizando como referencia diagnóstica la revisión de radiólogos expertos. Se comparó el desempeño del algoritmo frente a médicos de urgencias, tanto de forma independiente como asistida, y se midió el tiempo de lectura en ambos escenarios. /* indicadores */ Los indicadores de impacto clínico fueron la *precisión diagnóstica*, el *tiempo de lectura del diagnostico*, y la *priorización de casos sospechosos* en el flujo hospitalario. /* resultado */ Como resultado, el algoritmo mostró mejor rendimiento que los médicos solos y potenció significativamente su precisión y eficiencia diagnóstica cuando fue usado como herramienta de apoyo. /* conclusion */ El estudio concluye que el uso del deep learning como soporte en urgencias mejora la detección de neumonía y optimiza el flujo de atención, con beneficios clínicos tangibles. /* limitaciones */ Sin embargo, el estudio presenta limitaciones como muestra poblacional poco representativa, el reducido número de observadores, la generación de falsos positivos por el algoritmo y la variabilidad individual en la mejora del rendimiento clínico.

/* introducción */ En estudios previos realizados por #pc[@kim2020], se evaluó un algoritmo comercial de deep learning para detectar neumonía en radiografías de tórax en pacientes de urgencias. /* objetivo */ Determinar el rendimiento diagnóstico del algoritmo y su utilidad como apoyo a médicos no radiólogos. /* procedimiento */ Se estudiaron 377 pacientes en un hospital militar, comparando el desempeño del algoritmo con médicos de urgencias, con y sin asistencia, usando diagnóstico de radiólogos como referencia y midiendo el tiempo de lectura. /* indicadores */ Se evaluaron la *precisión diagnóstica*, el *tiempo de lectura del diagnóstico* y la *priorización de casos sospechosos*. /* resultado */ El algoritmo superó a los médicos actuando solos y mejoró significativamente su rendimiento cuando se usó como herramienta de apoyo. /* conclusion */ El deep learning mejora la detección de neumonía en urgencias y optimiza el flujo clínico cuando se integra como soporte diagnóstico. /* limitaciones */ Las limitaciones incluyen una muestra poco representativa, pocos observadores, generación de falsos positivos y variabilidad individual en los beneficios clínicos.

// menciona no decir mucho inteligencia artificial en las clinicas
// 3 indicadores ✅
//* introducción */ Según la investigación de #pc[@sendak2020], integrar herramientas basadas en deep learning en la práctica clínica cotidiana sigue siendo un desafío, especialmente para enfermedades críticas como complicaciones infecciosas graves derivadas de afecciones respiratorias, entre ellas la neumonía. /* objetivo */ El estudio tuvo como objetivo describir el proceso de implementación de Sepsis Watch, un sistema automatizado basado en deep learning para detectar y gestionar complicaciones infecciosas graves. /* procedimiento parafrasear */ Para ello, se llevó a cabo un proceso de más de dos años en el sistema de salud Duke Health, siguiendo un enfoque de “sistema de salud que aprende”. Se desarrolló un nuevo modelo predictivo y se creó una infraestructura tecnológica que integraba datos clínicos en tiempo real. El flujo de trabajo fue rediseñado para incluir a un equipo de enfermería especializado como filtro de alertas, y se aplicaron estrategias intensivas de gestión del cambio, formación y gobernanza clínica. Además, se estableció un plan de evaluación mixto con métodos cualitativos y cuantitativos. /* indicadores */ Los indicadores fueron el *cumplimiento de los paquetes de tratamiento de sepsis*, la *reducción del tiempo de respuesta* para activar protocolos de atención y la *aceptación del sistema por parte del personal clínico*. /* resultado */ Como resultado del estudio, Sepsis Watch fue integrado exitosamente en la atención clínica rutinaria logrando pasar del concepto a la práctica en un entorno real, esta implementación se logró gracias al compromiso activo del personal clínico. Para favorecer su aceptación, se evitó intencionalmente el uso del término "inteligencia artificial" en las comunicaciones. /* conclusion */ El estudio concluye que el desarrollo del algoritmo es solo una parte del proceso; la adopción real requiere rediseñar flujos de trabajo, capacitar al personal, establecer estructuras de gobernanza y cultivar la aceptación. Estas experiencias pueden orientar a otros centros que busquen aplicar inteligencia artificial en la atención de enfermedades respiratorias agudas. /* limitaciones */ Las principales limitaciones incluyen la realización del estudio en un único centro, la falta de datos definitivos sobre impacto clínico y económico, los desafíos metodológicos para reentrenar modelos en entornos cambiantes y la necesidad de evaluar su aplicación en otros servicios y hospitales.

/* introducción */ Según la investigación de #pc[@sendak2020], integrar modelos de deep learning en la práctica clínica sigue siendo complejo, especialmente para enfermedades graves como la neumonía. /* objetivo */ Describir la implementación de Sepsis Watch, un sistema automatizado basado en deep learning para detectar y gestionar complicaciones infecciosas. /* procedimiento */ En Duke Health se desarrolló un modelo predictivo e infraestructura con datos clínicos en tiempo real; se rediseñó el flujo de trabajo, se integró un equipo de enfermería para filtrar alertas y se aplicaron estrategias de gestión del cambio, formación y gobernanza clínica, evaluado con métodos mixtos. /* indicadores */ Se evaluó el *cumplimiento de tratamientos*, el *tiempos de respuesta de diagnóstico* y la *aceptación del sistema por el personal*. /* resultado */ Sepsis Watch fue implementado con éxito en la práctica clínica real, gracias al compromiso del equipo médico y evitando el término "IA" para mejorar su aceptación. /* conclusion */ La adopción de IA requiere más que algoritmos: implica rediseño organizacional, capacitación, gobernanza y estrategias de aceptación que pueden guiar a otros centros. /* limitaciones */ Las limitaciones incluyen realización en un solo centro, falta de datos sobre impacto clínico/económico, retos para reentrenar modelos y necesidad de validación en otros entornos.

// 4 indicadores ✅
//* introducción */ #pc[@sim2022] en su estudio, exploran cómo una herramienta de inteligencia artificial puede ser utilizada para detectar signos de infección pulmonar en radiografías de tórax, en el contexto de la pandemia por COVID-19. /* objetivo */ El estudio tuvo como objetivo desarrollar un modelo de IA capaz de identificar con precisión neumonía en radiografías de tórax, evaluar su rendimiento en condiciones clínicas reales y medir su impacto en la eficiencia operativa, especialmente en el tiempo de entrega de los informes médicos. /* procedimiento */ Se utilizó un modelo de deep learning basado en la arquitectura DenseNet, primero preentrenado con un conjunto público (ChestX-ray14) y luego ajustado con más de 4,000 radiografías internas. El modelo fue desplegado en el entorno hospitalario y se integró automáticamente al flujo de trabajo, reordenando los estudios con hallazgos sospechosos para que los radiólogos los priorizaran. Se evaluó el rendimiento del modelo en un conjunto de más de 3,700 radiografías clínicas y se compararon los tiempos de entrega antes y después de su implementación. /* indicadores */ Los indicadores utilizados fueron la *tiempo promedio de elaboración de informes radiológicos*, el *rendimiento de diagnóstico* y la *priorización de casos potencialmente graves*. /* resultado */ Como resultado, el sistema logró integrarse exitosamente en la práctica clínica, manteniendo su precisión diagnóstica incluso en condiciones reales y mejorando la velocidad de atención. Esto lo posiciona como una herramienta útil para agilizar la respuesta médica en contextos de alta demanda. /* conclusion */ El estudio concluye que la implementación de modelos de IA para el análisis de imágenes médicas es viable y beneficiosa, siempre que se mantenga el control humano en el proceso diagnóstico. La IA actuó como un filtro inicial eficaz, acelerando la evaluación de casos urgentes sin comprometer la calidad del diagnóstico. /* limitaciones */Sin embargo, el estudio presenta ciertas limitaciones, el modelo fue desarrollado e implementado en un solo centro, no puede diferenciar entre tipos específicos de neumonía, no incorpora datos clínicos adicionales como síntomas o antecedentes, y no está validado para su uso en población pediátrica.

/* introducción */ #pc[@sim2022] explora el uso de IA para detectar infecciones pulmonares en radiografías de tórax durante la pandemia por COVID-19. /* objetivo */ Desarrollar y evaluar un modelo de IA que identifique neumonía con precisión, mida su impacto en la práctica clínica real y en la rapidez de entrega de informes. /* procedimiento */ Se utilizó un modelo DenseNet preentrenado con ChestX-ray14 y ajustado con más de 4,000 radiografías internas; fue integrado al flujo hospitalario para priorizar casos sospechosos, evaluado en 3,700 estudios clínicos y comparado con tiempos previos. /* indicadores */ Se midieron el *tiempo promedio de elaboración de informes*, el *rendimiento diagnóstico* y la *priorización de casos graves*. /* resultado */ El sistema mantuvo su precisión en condiciones reales y redujo los tiempos de atención, demostrando utilidad en contextos clínicos de alta demanda. /* conclusion */ Se concluye que modelos de IA pueden integrarse eficazmente en el diagnóstico médico como filtro inicial, mejorando eficiencia sin comprometer la calidad, siempre bajo supervisión humana. /* limitaciones */ Las limitaciones incluyen que fue implementado en un solo centro, no distingue tipos de neumonía, no usa datos clínicos adicionales y no está validado en población pediátrica.


// 5 federado ✅
//* introducción */ Según la investigación de #pc[@kareem2023], se explora la viabilidad del aprendizaje federado como una estrategia para entrenar modelos de detección de neumonía a partir de imágenes médicas sin comprometer la privacidad de los datos de los pacientes. /* objetivo */ El objetivo principal del estudio es desarrollar y evaluar un marco de aprendizaje federado que permita entrenar modelos de clasificación de neumonía usando datos distribuidos entre múltiples instituciones médicas, cumpliendo con normativas como el GDPR (General Data Protection Regulation) y la DPA (Data Processing Agreement). /* procedimiento */ Se utilizó un conjunto de 5,856 radiografías de tórax clasificadas como "neumonía" o "normal". Las imágenes se preprocesaron y se entrenaron modelos CNN (ResNet-50, DenseNet, AlexNet, VGG19, e Inception). Se simularon cuatro clientes virtuales que entrenaban localmente sus modelos y luego enviaban los parámetros al servidor central. Este servidor agregaba los modelos para formar una versión global mejorada, repitiendo el proceso iterativamente./* resultado */ El modelo ResNet-50 entrenado bajo el marco de aprendizaje federado alcanzó una exactitud del 93%, mostrando un rendimiento comparable al de los modelos centralizados. DenseNet también tuvo un desempeño similar. Las diferencias de rendimiento fueron mínimas, lo que valida el enfoque federado como una solución viable. AlexNet e Inception presentaron una mayor caída en precisión bajo este esquema. /* conclusion */ El estudio demuestra que el aprendizaje federado permite entrenar modelos eficaces para la detección de neumonía en radiografías sin comprometer la privacidad de los datos. ResNet-50 y DenseNet se destacaron por su alto rendimiento dentro de este marco distribuido, lo que sugiere que el FL puede ser adoptado por instituciones médicas como una alternativa viable para el desarrollo colaborativo de modelos de IA. /* limitaciones */ El estudio advierte sobre limitaciones como la variabilidad en la calidad de los datos entre instituciones, la carga de comunicación entre nodos, la falta de estandarización en el aprendizaje federado, y el hecho de que la solución propuesta aún no cuenta con certificaciones regulatorias para su uso clínico.

/* introducción */ Según la investigación de #pc[@kareem2023], se analiza el aprendizaje federado como método para entrenar modelos de detección de neumonía sin comprometer la privacidad de los datos médicos. /* objetivo */ El estudio busca desarrollar y evaluar un marco de FL que permita entrenar modelos de clasificación de neumonía con datos distribuidos, cumpliendo con normativas como GDPR y DPA. /* procedimiento */ Se usaron 5,856 radiografías clasificadas como "neumonía" o "normal"; se entrenaron CNN (ResNet-50, DenseNet, AlexNet, VGG19, Inception) en cuatro clientes virtuales y se agregaron sus parámetros en un servidor central de forma iterativa. /* resultado */ ResNet-50 bajo FL alcanzó 93% de precisión, comparable al entrenamiento centralizado; DenseNet también fue competitivo, mientras que AlexNet e Inception mostraron menor rendimiento. /* conclusion */ El estudio confirma que FL permite entrenar modelos efectivos para detectar neumonía protegiendo la privacidad, destacando ResNet-50 y DenseNet como opciones viables para entornos colaborativos médicos. /* limitaciones */ Se reportan desafíos como variabilidad de datos entre instituciones, carga de comunicación, falta de estandarización del FL y ausencia de certificación clínica para la solución propuesta.


// 6 federado ✅ menciona la importancia de la sobre carga de los servidores por un modelo pesado
//* introducción */ En tal sentido #pc[@mabrouk2023], propone un enfoque que combina aprendizaje por ensamble con aprendizaje federado para mejorar el diagnóstico automático de neumonía a partir de radiografías de tórax, sin comprometer la privacidad de los datos clínicos.  /* objetivo */ El objetivo principal del estudio es diseñar y evaluar un marco de Aprendizaje Federado de Ensamble (EFL) que permita la colaboración entre múltiples instituciones médicas para entrenar modelos precisos y robustos de clasificación de neumonía, sin intercambiar datos sensibles. /* procedimiento */ Para ello, se simularon cinco nodos institucionales, cada uno entrenando ocho modelos CNN distintos en sus datos locales. Cada nodo seleccionó sus dos mejores modelos para crear un Modelo de Ensamble Local (LEL). Luego, estos modelos locales fueron compartidos con un servidor central, que los combinó para formar un Modelo de Ensamble Global (GEL). Finalmente, se comparó el desempeño del modelo EFL con un enfoque centralizado tradicional. /* resultado */ El modelo EFL alcanzó una exactitud del 96.63%, superando al mejor modelo centralizado (DenseNet121) que obtuvo un 95.03%. El rendimiento del modelo global mejoró consistentemente a lo largo de las rondas de entrenamiento federado, demostrando la efectividad del enfoque propuesto sin comprometer la privacidad. /* conclusion */ El estudio concluye que el aprendizaje federado de ensamble permite construir modelos de diagnóstico más precisos que los modelos centralizados, con la ventaja añadida de proteger los datos clínicos. Este enfoque puede ser extrapolado a otras aplicaciones médicas basadas en imágenes distribuidas y confidenciales. /* limitaciones */ Se identifican limitaciones relacionadas con la complejidad en la optimización del marco EFL y con desafíos técnicos como el posible colapso del servidor central bajo cargas altas y la falta de heterogeneidad en la simulación computacional de los nodos, lo que podría dificultar su implementación en contextos reales.

/* introducción */ En tal sentido #pc[@mabrouk2023], propone combinar aprendizaje por ensamble y federado para diagnosticar neumonía en radiografías sin comprometer la privacidad. /* objetivo */ El objetivo del estudio es diseñar y evaluar un marco de Aprendizaje Federado de Ensamble (EFL) que permita entrenar modelos robustos entre instituciones sin compartir datos sensibles. /* procedimiento */ Para ello, se simularon cinco nodos, cada uno entrenó ocho CNN y seleccionó sus dos mejores para formar un Modelo de Ensamble Local (LEL); estos se enviaron a un servidor central para crear un Modelo de Ensamble Global (GEL), comparado luego con un enfoque centralizado. /* resultado */ Como resultado, EFL alcanzó 96.63% de precisión, superando al modelo centralizado (95.03%) y mostrando mejoras consistentes sin comprometer privacidad. /* conclusion */ En conclusión, El aprendizaje federado de ensamble mejora la precisión del diagnóstico respecto a modelos centralizados y protege los datos, siendo aplicable a otras áreas médicas. /* limitaciones */ Se enfrentan desafíos como la complejidad del marco EFL, riesgo de sobrecarga del servidor central y falta de heterogeneidad en la simulación de los nodos.


// 7 federado - sera importante mencionar sobre la definicion de no-IID? ✅
///* introducción */ En tal sentido #pc[@riedel2023], plantea una arquitectura modificada basada en ResNet50 para hacer viable el aprendizaje federado con privacidad diferencial en la detección de neumonía por COVID-19 a partir de radiografías de tórax.  /* objetivo */ El objetivo principal del estudio es evaluar la eficacia de una arquitectura llamada ResNetFed, diseñada para ser compatible con aprendizaje federado y mecanismos de privacidad diferencial, en la tarea de detección de neumonía por COVID-19, sin comprometer la privacidad de los datos clínicos. /* procedimiento */ Se utilizó el conjunto de datos COVIDx8, distribuido de forma no-IID (Independent and Identically Distributed) entre cinco silos simulados. Se modificó el modelo ResNet50 reemplazando sus capas de normalización por lotes con capas de identidad, para permitir su uso con privacidad diferencial. El modelo ResNetFed se entrenó localmente en cada silo y sus actualizaciones fueron agregadas por un servidor central mediante FedAvg durante 100 rondas. El rendimiento se comparó con modelos entrenados localmente y con un modelo centralizado entrenado con todos los datos. /* resultado */ ResNetFed obtuvo una exactitud media del 82.82%, superando ampliamente a los modelos locales (63%). Las mejoras fueron especialmente notorias en silos con datos escasos o desbalanceados, con incrementos de hasta 34.9 puntos porcentuales. Aunque el modelo centralizado alcanzó mayor precisión (98%), ResNetFed ofreció un rendimiento competitivo con mayor respeto por la privacidad. /* conclusion */ El estudio valida a ResNetFed como una solución viable y segura para el diagnóstico de neumonía por COVID-19 en contextos descentralizados. Su capacidad para superar modelos locales y adaptarse a datos no uniformemente distribuidos lo convierte en una herramienta prometedora para entornos clínicos colaborativos que requieren protección de datos. /* limitaciones */ No obstante, se identifican desafíos significativos, como el impacto de la distribución no-IID de los datos, la complejidad de ajustar hiperparámetros en entornos federados, la necesidad de adaptar arquitecturas preentrenadas para FL y las limitaciones en el análisis exploratorio de datos sensibles que permanecen inaccesibles directamente.

/* introducción */ En tal sentido #pc[@riedel2023], propone ResNetFed, una versión de ResNet50 adaptada para aprendizaje federado con privacidad diferencial en la detección de neumonía por COVID-19 a partir de radiografías de tórax. /* objetivo */ El estudio busca evaluar la eficacia de ResNetFed, compatible con federated learning y privacidad diferencial, sin comprometer los datos clínicos. /* procedimiento */ Se usó el dataset COVIDx8 distribuido no-IID en cinco silos simulados; se modificó ResNet50 reemplazando la normalización por lotes con capas de identidad y se entrenó localmente, agregando actualizaciones con FedAvg durante 100 rondas, comparado con modelos locales y uno centralizado. /* resultado */ ResNetFed alcanzó 82.82% de precisión, superando a los modelos locales (63%) y mostrando mejoras en silos con datos escasos, con menor precisión que el modelo centralizado (98%) pero mayor privacidad. /* conclusion */ En conclusión, se valida ResNetFed como una solución eficaz y segura en contextos clínicos descentralizados con datos distribuidos de forma no uniforme. /* limitaciones */ Sin embargo, persisten desafíos como la distribución no-IID, ajuste de hiperparámetros, adaptación de arquitecturas y análisis limitado de datos sensibles.

// 8 sin indicadores - habla sobre la detección de posible muerte por neumonía usando expedientes de laboratorio ❌
//* introducción */ Un antecedente relevante es el estudio de #pc[@baik2024], que desarrolla un modelo de inteligencia artificial basado en datos de laboratorio y clínicos para predecir la mortalidad en pacientes hospitalizados por neumonía.  /* objetivo */ El objetivo fue crear un modelo predictivo temprano de mortalidad por neumonía, demostrando que los resultados de laboratorio, integrados mediante técnicas de IA, pueden ofrecer predicciones precisas y útiles para la toma de decisiones clínicas. /* procedimiento */ Se recopilaron datos de 1,065 pacientes adultos con neumonía hospitalizados entre 2020 y 2022. Se procesaron 76 variables para crear un conjunto de datos estructurado con 80 940 instancias. Se entrenaron modelos ML (XGBoost, CatBoost, LGBM, RF, SVM, KNN) y un modelo DL (Multilayer Perceptron). Posteriormente, se desarrollaron dos modelos de ensamble: uno optimizado para AUROC (votación suave) y otro para F1-score (votación dura). Se aplicaron técnicas de explicación (SHAP) para identificar variables clínicas clave en la predicción. /* resultado */ Como resultado, el modelo de ensamble alcanzó un AUROC de 0.9006, precisión del 90% y F1-score de 0.81, superando a todos los modelos individuales. XGBoost fue el modelo individual más eficaz. /* conclusion */ El estudio muestra que modelos de ensamble basados en técnicas de ML pueden proporcionar predicciones de mortalidad precisas a partir de datos clínicos rutinarios. Reafirma el potencial de la IA como herramienta complementaria para mejorar el juicio clínico, especialmente al aprovechar datos subestimados como los de laboratorio. /* limitaciones */ Sin embargo, el estudio presenta ciertas limitaciones, el modelo se basa en datos de un único hospital, lo que limita su generalización. Además, el estudio retrospectivo implica riesgos de calidad en los datos. La inclusión de casos de neumonía por COVID-19 puede afectar la aplicabilidad a otros tipos de neumonía, y la exclusión de menores de 19 años limita su uso en población pediátrica.


// contexto nacional 1 ------------------------------------------

Respecto a estudios de índole nacional se ha considerado el siguiente:

// 9 indicadores ✅
//* introducción */ #pc[@flores2022] en su estudio, evaluó el impacto del uso de una aplicación móvil basada en redes neuronales convolucionales en el proceso de diagnóstico de neumonía, con énfasis en su utilidad para acelerar la detección y reducir la carga asistencial del personal médico.  /* objetivo */ El objetivo del estudio fue determinar la influencia de la aplicación móvil "Diagnost", basada en una CNN, en la detección de neumonía, especialmente en términos de rapidez diagnóstica, reducción de asistencia médica requerida y precisión del diagnóstico. /* procedimiento */ Se realizó un estudio experimental con diseño pre-test/post-test y dos grupos (control y experimental, n=33 cada uno). Se entrenó un modelo CNN (DenseNet) con imágenes de radiografías de tórax, y se integró en una app móvil para Android./* indicadores */ Los tres indicadores clínicos evaluados fueron *tiempo de detección*; *precisión del diagnóstico* y *reducción de asistencia médica*. /* resultado */Por consiguiente, la aplicación permitió una detección significativamente más temprana de la neumonía y redujo la asistencia médica requerida, pero no mejoró la precisión diagnóstica en comparación con el grupo control. /* conclusion */ En conclusión, "Diagnost" demostró ser eficaz para acelerar el diagnóstico y optimizar recursos médicos, aunque no logró mejorar la precisión del diagnóstico respecto a los métodos tradicionales./* limitaciones */ El estudio presenta una limitación importante, el modelo no era lo suficientemente preciso. Aunque útil para agilizar procesos, la herramienta no supera la capacidad diagnóstica del personal médico, lo que señala una necesidad de perfeccionamiento técnico del modelo.

/* introducción */ #pc[@flores2022] evaluó el impacto de una app móvil con CNN para diagnosticar neumonía, enfocándose en acelerar la detección y aliviar la carga médica. /* objetivo */ Determinar la influencia de "Diagnost" (basada en DenseNet) en rapidez diagnóstica, precisión y reducción de asistencia médica. /* procedimiento */ Se usó un diseño experimental pre-test/post-test con grupos control y experimental (n=33), integrando el modelo en Android. /* indicadores */ Se evaluaron el *tiempo de detección*, la *precisión diagnóstica* y la *reducción de asistencia médica*. /* resultado */ La app mejoró el tiempo diagnóstico y redujo la asistencia requerida, pero no aumentó la precisión respecto al grupo control. /* conclusion */ "Diagnost" fue útil para acelerar diagnósticos y optimizar recursos, aunque sin mejorar la precisión sobre métodos tradicionales. /* limitaciones */ El modelo no alcanzó la precisión del personal médico, destacando la necesidad de mejorar técnicamente la herramienta.
