#import "@local/utp-doc:1.0.0": pc

#pagebreak()

= Revisión de la literatura actual o estado del arte // maximo 5 paginas
Diversos estudios y proyectos han abordado la necesidad de desarrollar sistemas de detección de neumonía usando modelos de Deep Learning, demostrando su efectividad para diagnosticar la enfermedad.

// contexto internacional 8 ------------------------------------------

// todo: agregar a marco teorico CNN
// 1 sin indicadores ✅
/* introducción */ #pc[@hwang2020] presenta una revisión sobre el uso de deep learning en radiología, con foco en radiografías de tórax y tomografías computarizadas. /* objetivo */ Introducir las aplicaciones clínicas del deep learning en la práctica diaria. /* procedimiento */ Se realizó una revisión narrativa de literatura sobre algoritmos CNN y su integración en flujos clínicos. /* resultado */ Se halló que el deep learning puede igualar o superar a radiólogos expertos en detección de enfermedades pulmonares, cribado, pronóstico y mejora de imagen. /* conclusion */ Aunque emergente, esta tecnología tiene alto potencial en radiología torácica, y su adopción requiere que los radiólogos comprendan sus capacidades y límites. /* limitaciones */ Las barreras incluyen falta de explicabilidad, escasa validación clínica, poca evidencia de impacto en pacientes y dificultad de integración con sistemas existentes.

// 2 indicadores ✅
/* introducción */ En estudios previos realizados por #pc[@kim2020], se evaluó un algoritmo comercial de deep learning para detectar neumonía en radiografías de tórax en pacientes de urgencias. /* objetivo */ Determinar el rendimiento diagnóstico del algoritmo y su utilidad como apoyo a médicos no radiólogos. /* procedimiento */ Se estudiaron 377 pacientes en un hospital militar, comparando el desempeño del algoritmo con médicos de urgencias, con y sin asistencia, usando diagnóstico de radiólogos como referencia y midiendo el tiempo de lectura. /* indicadores */ Se evaluaron la #emph[precisión diagnóstica], el #emph[tiempo de lectura del diagnóstico] y la #emph[priorización de casos sospechosos]. /* resultado */ El algoritmo superó a los médicos actuando solos y mejoró significativamente su rendimiento cuando se usó como herramienta de apoyo. /* conclusion */ El deep learning mejora la detección de neumonía en urgencias y optimiza el flujo clínico cuando se integra como soporte diagnóstico. /* limitaciones */ Las limitaciones incluyen una muestra poco representativa, pocos observadores, generación de falsos positivos y variabilidad individual en los beneficios clínicos.

// menciona no decir mucho inteligencia artificial en las clinicas
// 3 indicadores ✅
/* introducción */ Según la investigación de #pc[@sendak2020], integrar modelos de deep learning en la práctica clínica sigue siendo complejo, especialmente para enfermedades graves como la neumonía. /* objetivo */ Describir la implementación de Sepsis Watch, un sistema automatizado basado en deep learning para detectar y gestionar complicaciones infecciosas. /* procedimiento */ En Duke Health se desarrolló un modelo predictivo e infraestructura con datos clínicos en tiempo real; se rediseñó el flujo de trabajo, se integró un equipo de enfermería para filtrar alertas y se aplicaron estrategias de gestión del cambio, formación y gobernanza clínica, evaluado con métodos mixtos. /* indicadores */ Se evaluó el #emph[cumplimiento de tratamientos], el #emph[tiempos de respuesta de diagnóstico] y la #emph[aceptación del sistema por el personal]. /* resultado */ Sepsis Watch fue implementado con éxito en la práctica clínica real, gracias al compromiso del equipo médico y evitando el término \"IA\" para mejorar su aceptación. /* conclusion */ La adopción de IA requiere más que algoritmos: implica rediseño organizacional, capacitación, gobernanza y estrategias de aceptación que pueden guiar a otros centros. /* limitaciones */ Las limitaciones incluyen realización en un solo centro, falta de datos sobre impacto clínico/económico, retos para reentrenar modelos y necesidad de validación en otros entornos.

// 4 indicadores ✅
/* introducción */ #pc[@sim2022] explora el uso de IA para detectar infecciones pulmonares en radiografías de tórax durante la pandemia por COVID-19. /* objetivo */ Desarrollar y evaluar un modelo de IA que identifique neumonía con precisión, mida su impacto en la práctica clínica real y en la rapidez de entrega de informes. /* procedimiento */ Se utilizó un modelo DenseNet preentrenado con ChestX-ray14 y ajustado con más de 4,000 radiografías internas; fue integrado al flujo hospitalario para priorizar casos sospechosos, evaluado en 3,700 estudios clínicos y comparado con tiempos previos. /* indicadores */ Se midieron el #emph[tiempo promedio de elaboración de informes], el #emph[rendimiento diagnóstico] y la #emph[priorización de casos graves]. /* resultado */ El sistema mantuvo su precisión en condiciones reales y redujo los tiempos de atención, demostrando utilidad en contextos clínicos de alta demanda. /* conclusion */ Se concluye que modelos de IA pueden integrarse eficazmente en el diagnóstico médico como filtro inicial, mejorando eficiencia sin comprometer la calidad, siempre bajo supervisión humana. /* limitaciones */ Las limitaciones incluyen que fue implementado en un solo centro, no distingue tipos de neumonía, no usa datos clínicos adicionales y no está validado en población pediátrica.


// 5 federado ✅
/* introducción */ Según la investigación de #pc[@kareem2023], se analiza el aprendizaje federado como método para entrenar modelos de detección de neumonía sin comprometer la privacidad de los datos médicos. /* objetivo */ El estudio busca desarrollar y evaluar un marco de FL que permita entrenar modelos de clasificación de neumonía con datos distribuidos, cumpliendo con normativas como GDPR y DPA. /* procedimiento */ Se usaron 5,856 radiografías clasificadas como \"neumonía\" o \"normal\"; se entrenaron CNN (ResNet-50, DenseNet, AlexNet, VGG19, Inception) en cuatro clientes virtuales y se agregaron sus parámetros en un servidor central de forma iterativa. /* resultado */ ResNet-50 bajo FL alcanzó 93% de precisión, comparable al entrenamiento centralizado; DenseNet también fue competitivo, mientras que AlexNet e Inception mostraron menor rendimiento. /* conclusion */ El estudio confirma que FL permite entrenar modelos efectivos para detectar neumonía protegiendo la privacidad, destacando ResNet-50 y DenseNet como opciones viables para entornos colaborativos médicos. /* limitaciones */ Se reportan desafíos como variabilidad de datos entre instituciones, carga de comunicación, falta de estandarización del FL y ausencia de certificación clínica para la solución propuesta.


// 6 federado ✅ menciona la importancia de la sobre carga de los servidores por un modelo pesado
/* introducción */ En tal sentido #pc[@mabrouk2023], propone combinar aprendizaje por ensamble y federado para diagnosticar neumonía en radiografías sin comprometer la privacidad. /* objetivo */ El objetivo del estudio es diseñar y evaluar un marco de Aprendizaje Federado de Ensamble (EFL) que permita entrenar modelos robustos entre instituciones sin compartir datos sensibles. /* procedimiento */ Para ello, se simularon cinco nodos, cada uno entrenó ocho CNN y seleccionó sus dos mejores para formar un Modelo de Ensamble Local (LEL); estos se enviaron a un servidor central para crear un Modelo de Ensamble Global (GEL), comparado luego con un enfoque centralizado. /* resultado */ Como resultado, EFL alcanzó 96.63% de precisión, superando al modelo centralizado (95.03%) y mostrando mejoras consistentes sin comprometer privacidad. /* conclusion */ En conclusión, El aprendizaje federado de ensamble mejora la precisión del diagnóstico respecto a modelos centralizados y protege los datos, siendo aplicable a otras áreas médicas. /* limitaciones */ Se enfrentan desafíos como la complejidad del marco EFL, riesgo de sobrecarga del servidor central y falta de heterogeneidad en la simulación de los nodos.


// 7 federado - sera importante mencionar sobre la definicion de no-IID? ✅
/* introducción */ En tal sentido #pc[@riedel2023], propone ResNetFed, una versión de ResNet50 adaptada para aprendizaje federado con privacidad diferencial en la detección de neumonía por COVID-19 a partir de radiografías de tórax. /* objetivo */ El estudio busca evaluar la eficacia de ResNetFed, compatible con federated learning y privacidad diferencial, sin comprometer los datos clínicos. /* procedimiento */ Se usó el dataset COVIDx8 distribuido no-IID en cinco silos simulados; se modificó ResNet50 reemplazando la normalización por lotes con capas de identidad y se entrenó localmente, agregando actualizaciones con FedAvg durante 100 rondas, comparado con modelos locales y uno centralizado. /* resultado */ ResNetFed alcanzó 82.82% de precisión, superando a los modelos locales (63%) y mostrando mejoras en silos con datos escasos, con menor precisión que el modelo centralizado (98%) pero mayor privacidad. /* conclusion */ En conclusión, se valida ResNetFed como una solución eficaz y segura en contextos clínicos descentralizados con datos distribuidos de forma no uniforme. /* limitaciones */ Sin embargo, persisten desafíos como la distribución no-IID, ajuste de hiperparámetros, adaptación de arquitecturas y análisis limitado de datos sensibles.


// contexto nacional 1 ------------------------------------------

Respecto a estudios de índole nacional se ha considerado el siguiente:

// 9 indicadores ✅
/* introducción */ #pc[@flores2022] evaluó el impacto de una app móvil con CNN para diagnosticar neumonía, enfocándose en acelerar la detección y aliviar la carga médica. /* objetivo */ Determinar la influencia de Diagnost (basada en DenseNet) en rapidez diagnóstica, precisión y reducción de asistencia médica. /* procedimiento */ Se usó un diseño experimental pre-test/post-test con grupos control y experimental (n=33), integrando el modelo en Android. /* indicadores */ Se evaluaron el #emph[tiempo de detección], la #emph[precisión diagnóstica] y la #emph[reducción de asistencia médica]. /* resultado */ La app mejoró el tiempo diagnóstico y redujo la asistencia requerida, pero no aumentó la precisión respecto al grupo control. /* conclusion */ Diagnost fue útil para acelerar diagnósticos y optimizar recursos, aunque sin mejorar la precisión sobre métodos tradicionales. /* limitaciones */ El modelo no alcanzó la precisión del personal médico, destacando la necesidad de mejorar técnicamente la herramienta.
