# clinica 1
c1: "Clínica" {
    pacs: PACS {
        icon: "https://www.svgrepo.com/show/148158/lungs-radiography.svg"
    }
    user: Clinica 1 {
        shape: Person
    }
    model: "" {
      icon: https://www.svgrepo.com/show/450794/deep-learning.svg
    }
    pacs -> model: Compartir radiografias
    model -> user: Entrenar modelo
}

# clinica 2
c2: "Clínica"{
    pacs: PACS {
        icon: "https://www.svgrepo.com/show/148158/lungs-radiography.svg"
    }
    user: Clinica 2 {
        shape: Person
    }
    model: "" {
      icon: https://www.svgrepo.com/show/450794/deep-learning.svg
    }
    pacs -> model: Compartir radiografias
    model -> user: Entrenar modelo
}

# server
central_server: "Servidor federado" {
    server: Cloud server {
        shape: cloud
        #icon: "https://assets.streamlinehq.com/image/private/w_300,h_300,ar_1/f_auto/v1/icons/logos/fastapi-91dvq8q5ewijkczjmd9bcb.png/fastapi-ggmxtn5w3qqwks1i5jnx2p.png?_a=DATAdtAAZAA0"
    }
    
    model: Modelo central {
      icon: https://www.svgrepo.com/show/450794/deep-learning.svg
    }
    db: Base de datos {
      shape: cylinder
      # icon: https://www.vectorlogo.zone/logos/postgresql/postgresql-icon.svg
    }
    server -> db: guardando parametros
    server -> model: promediando el aprendizaje
}

# ------------------------------------

central_server.model -> c1.model: Compartir aprendizaje
central_server.model -> c2.model: Compartir aprendizaje

c1.user -> central_server.server: Enviar aprendizaje
c2.user -> central_server.server: Enviar aprendizaje
