"""
# CRISP-DM
A: (1) Business understanding
B: (2) Data understanding
C: (3) Data preparation
D: (4) Modeling
E: (5) Evaluation
F: (6) xd

A -> B
B -> A
B -> C
C -> D
D -> C
D -> E
E -> A
E -> F
"""

1: Problem Definition
2: Data Collection
3: Data Cleaning and Preprocessing
4: Exploratory Data Analysis (EDA)
5: Feature Engineering and Selection
6: Model Selection
7: Model Training
8: Model Evaluation and Tuning
9: Model Deployment
10: Model Monitoring and Maintenance

1 -> 2
2 -> 3
3 -> 4
4 -> 5
5 -> 6
6 -> 7
7 -> 8
8 -> 9
9 -> 10
10 -> 1
